POST http://localhost:3001/employee
Content-Type: application/json

{
    "fullName":"Petar Jovanov",
    "email":"pera@gmail.com",
    "phoneNumber":"+387657598521",
    "dateOfBirth":"04.12.1995",
    "monthlySalary": 1600,
    "tasks": [
        "640a34c7646004eeabdb9176"
    ],
    "department": "640b05c7628c9f4d6563f053"
}

###

POST http://localhost:3001/task
Content-Type: application/json

{
    "title":"test",
    "description":"test",
    "assignee":"640daae910767700f0ae1b1f",
    "isFinished":"true",
    "dueDate": "2023-02-23T12:00:00Z"
}

###

GET http://localhost:3001/task/all

###
DELETE  http://localhost:3001/task/640a0c719c39f0b9e7244a5b

###

GET http://localhost:3001/employee/averageSalary

###
GET http://localhost:3001/employee/all

###
GET http://localhost:3001/employee/640a147c2fe941bbd072998f

###
DELETE  http://localhost:3001/employee/640a18b68da7fbbbc4a4d9bc

###
POST http://localhost:3001/department
Content-Type: application/json

{
    "departmentName": "Graphic Designers",
    "employees": [
        "640b0782412a36083c4183dc",
        "640b0cd8412a36083c4183e1"
    ]
}


###
GET http://localhost:3001/department/all


###
GET http://localhost:3001/employee/topFive




